apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serviceb-internal
spec:
  hosts:
    - serviceb
  http:
  - route:
    - destination:
        host: serviceb
        subset: v1
      weight: 100
    mirror:
      host: serviceb
      subset: v2
