apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: servicea
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: servicea-v1
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 7
