apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: serviceb-internal
spec:
  hosts:
  - serviceb
  http:
  - match:
    - headers:
        Segment:
          exact: Platinum
    route:
    - destination:
        host: serviceb
        subset: v1

  - match:
    - headers:
        Segment:
          exact: Gold
    route:
    - destination:
        host: serviceb
        subset: v2
  - route:
    - destination:
        host: serviceb
        subset: v3
